const stateList = [
  { value: 'andhra pradesh', label: 'Andhra Pradesh', code: 'AP' },
  { value: 'arunachal pradesh', label: 'Arunachal Pradesh', code: 'AR' },
  { value: 'assam', label: 'Assam', code: 'AS' },
  { value: 'bihar', label: 'Bihar', code: 'BR' },
  { value: 'chhattisgarh', label: 'Chhattisgarh', code: 'CG' },
  { value: 'goa', label: 'Goa', code: 'GA' },
  { value: 'gujarat', label: 'Gujarat', code: 'GJ' },
  { value: 'haryana', label: 'Haryana', code: 'HR' },
  { value: 'himachal pradesh', label: 'Himachal Pradesh', code: 'HP' },
  { value: 'jharkhand', label: 'Jharkhand', code: 'JH' },
  { value: 'karnataka', label: 'Karnataka', code: 'KA' },
  { value: 'kerala', label: 'Kerala', code: 'KL' },
  { value: 'madhya pradesh', label: 'Madhya Pradesh', code: 'MP' },
  { value: 'maharashtra', label: 'Maharashtra', code: 'MH' },
  { value: 'manipur', label: 'Manipur', code: 'MN' },
  { value: 'meghalaya', label: 'Meghalaya', code: 'ML' },
  { value: 'mizoram', label: 'Mizoram', code: 'MZ' },
  { value: 'nagaland', label: 'Nagaland', code: 'NL' },
  { value: 'odisha', label: 'Odisha', code: 'OR' },
  { value: 'punjab', label: 'Punjab', code: 'PB' },
  { value: 'rajasthan', label: 'Rajasthan', code: 'RJ' },
  { value: 'sikkim', label: 'Sikkim', code: 'SK' },
  { value: 'tamil nadu', label: 'Tamil Nadu', code: 'TN' },
  { value: 'telangana', label: 'Telangana', code: 'TG' },
  { value: 'tripura', label: 'Tripura', code: 'TR' },
  { value: 'uttar pradesh', label: 'Uttar Pradesh', code: 'UP' },
  { value: 'uttarakhand', label: 'Uttarakhand', code: 'UK' },
  { value: 'west bengal', label: 'West Bengal', code: 'WB' },
  // Union Territories
  {
    value: 'andaman and nicobar islands',
    label: 'Andaman and Nicobar Islands',
    code: 'AN',
  },
  { value: 'chandigarh', label: 'Chandigarh', code: 'CH' },
  {
    value: 'dadra and nagar haveli and daman and diu',
    label: 'Dadra and Nagar Haveli and Daman and Diu',
    code: 'DN',
  },
  { value: 'delhi', label: 'Delhi', code: 'DL' },
  { value: 'jammu and kashmir', label: 'Jammu and Kashmir', code: 'JK' },
  { value: 'ladakh', label: 'Ladakh', code: 'LA' },
  { value: 'lakshadweep', label: 'Lakshadweep', code: 'LD' },
  { value: 'puducherry', label: 'Puducherry', code: 'PY' },
];

export default stateList;
